In [1]:
import polars as pl
import polars.selectors as cs
import soccerdata as sd
import matplotlib.pyplot as plt
import sklearn as skl
import pandas as pd
import numpy as np
import pyarrow
import seaborn as sb
import csv
import socceraction.spadl as spadl

from whoscored_patch import apply_whoscored_json_patch

apply_whoscored_json_patch()  # restart kernel if you change whoscored_patch.py

[08/23/26 16:41:03] INFO     No custom team name replacements found. You can configure these in       ]8;id=3503336;file:///home/caff/Documents/footy_analysis/.venv/lib/python3.12/site-packages/soccerdata/_config.py\_config.py]8;;\:]8;id=3503337;file:///home/caff/Documents/footy_analysis/.venv/lib/python3.12/site-packages/soccerdata/_config.py#92\92]8;;\
                             /home/caff/soccerdata/config/teamname_replacements.json.

                    INFO     No custom league dict found. You can configure additional leagues in    ]8;id=3503343;file:///home/caff/Documents/footy_analysis/.venv/lib/python3.12/site-packages/soccerdata/_config.py\_config.py]8;;\:]8;id=3503344;file:///home/caff/Documents/footy_analysis/.venv/lib/python3.12/site-packages/soccerdata/_config.py#190\190]8;;\
                             /home/caff/soccerdata/config/league_dict.json.

In [2]:
ws = sd.WhoScored(
    leagues="ENG-Premier League",
    seasons=2026,
    path_to_browser="/usr/bin/chromium",
)

[08/23/26 16:41:04] INFO     Saving cached data to /home/caff/soccerdata/data/WhoScored              ]8;id=3503351;file:///home/caff/Documents/footy_analysis/.venv/lib/python3.12/site-packages/soccerdata/_common.py\_common.py]8;;\:]8;id=3503352;file:///home/caff/Documents/footy_analysis/.venv/lib/python3.12/site-packages/soccerdata/_common.py#250\250]8;;\

In [3]:
epl_schedule = ws.read_schedule()

[08/23/26 16:41:20] INFO     Retrieving calendar for ENG-Premier League 2627                       ]8;id=3503359;file:///home/caff/Documents/footy_analysis/.venv/lib/python3.12/site-packages/soccerdata/whoscored.py\whoscored.py]8;;\:]8;id=3503360;file:///home/caff/Documents/footy_analysis/.venv/lib/python3.12/site-packages/soccerdata/whoscored.py#366\366]8;;\

[08/23/26 16:41:51] INFO     [1/10] Retrieving fixtures for ENG-Premier League 2627                ]8;id=3503366;file:///home/caff/Documents/footy_analysis/.venv/lib/python3.12/site-packages/soccerdata/whoscored.py\whoscored.py]8;;\:]8;id=3503367;file:///home/caff/Documents/footy_analysis/.venv/lib/python3.12/site-packages/soccerdata/whoscored.py#397\397]8;;\

[08/23/26 16:42:02] INFO     [2/10] Retrieving fixtures for ENG-Premier League 2627                ]8;id=3503372;file:///home/caff/Documents/footy_analysis/.venv/lib/python3.12/site-packages/soccerdata/whoscored.py\whoscored.py]8;;\:]8;id=3503373;file:///home/caff/Documents/footy_analysis/.venv/lib/python3.12/site-packages/soccerdata/whoscored.py#397\397]8;;\

[08/23/26 16:42:12] INFO     [3/10] Retrieving fixtures for ENG-Premier League 2627                ]8;id=3503378;file:///home/caff/Documents/footy_analysis/.venv/lib/python3.12/site-packages/soccerdata/whoscored.py\whoscored.py]8;;\:]8;id=3503379;file:///home/caff/Documents/footy_analysis/.venv/lib/python3.12/site-packages/soccerdata/whoscored.py#397\397]8;;\

[08/23/26 16:42:23] INFO     [4/10] Retrieving fixtures for ENG-Premier League 2627                ]8;id=3503384;file:///home/caff/Documents/footy_analysis/.venv/lib/python3.12/site-packages/soccerdata/whoscored.py\whoscored.py]8;;\:]8;id=3503385;file:///home/caff/Documents/footy_analysis/.venv/lib/python3.12/site-packages/soccerdata/whoscored.py#397\397]8;;\

[08/23/26 16:42:34] INFO     [5/10] Retrieving fixtures for ENG-Premier League 2627                ]8;id=3503390;file:///home/caff/Documents/footy_analysis/.venv/lib/python3.12/site-packages/soccerdata/whoscored.py\whoscored.py]8;;\:]8;id=3503391;file:///home/caff/Documents/footy_analysis/.venv/lib/python3.12/site-packages/soccerdata/whoscored.py#397\397]8;;\

[08/23/26 16:42:47] INFO     [6/10] Retrieving fixtures for ENG-Premier League 2627                ]8;id=3503396;file:///home/caff/Documents/footy_analysis/.venv/lib/python3.12/site-packages/soccerdata/whoscored.py\whoscored.py]8;;\:]8;id=3503397;file:///home/caff/Documents/footy_analysis/.venv/lib/python3.12/site-packages/soccerdata/whoscored.py#397\397]8;;\

[08/23/26 16:42:57] INFO     [7/10] Retrieving fixtures for ENG-Premier League 2627                ]8;id=3503402;file:///home/caff/Documents/footy_analysis/.venv/lib/python3.12/site-packages/soccerdata/whoscored.py\whoscored.py]8;;\:]8;id=3503403;file:///home/caff/Documents/footy_analysis/.venv/lib/python3.12/site-packages/soccerdata/whoscored.py#397\397]8;;\

[08/23/26 16:43:07] INFO     [8/10] Retrieving fixtures for ENG-Premier League 2627                ]8;id=3503408;file:///home/caff/Documents/footy_analysis/.venv/lib/python3.12/site-packages/soccerdata/whoscored.py\whoscored.py]8;;\:]8;id=3503409;file:///home/caff/Documents/footy_analysis/.venv/lib/python3.12/site-packages/soccerdata/whoscored.py#397\397]8;;\

[08/23/26 16:43:16] INFO     [9/10] Retrieving fixtures for ENG-Premier League 2627                ]8;id=3503414;file:///home/caff/Documents/footy_analysis/.venv/lib/python3.12/site-packages/soccerdata/whoscored.py\whoscored.py]8;;\:]8;id=3503415;file:///home/caff/Documents/footy_analysis/.venv/lib/python3.12/site-packages/soccerdata/whoscored.py#397\397]8;;\

[08/23/26 16:43:30] INFO     [10/10] Retrieving fixtures for ENG-Premier League 2627               ]8;id=3503420;file:///home/caff/Documents/footy_analysis/.venv/lib/python3.12/site-packages/soccerdata/whoscored.py\whoscored.py]8;;\:]8;id=3503421;file:///home/caff/Documents/footy_analysis/.venv/lib/python3.12/site-packages/soccerdata/whoscored.py#397\397]8;;\

[08/23/26 16:43:38] WARNING  /home/caff/Documents/footy_analysis/.venv/lib/python3.12/site-packages ]8;id=3503428;file:///home/caff/.pyenv/versions/3.12.13/lib/python3.12/warnings.py\warnings.py]8;;\:]8;id=3503429;file:///home/caff/.pyenv/versions/3.12.13/lib/python3.12/warnings.py#112\112]8;;\
                             /soccerdata/whoscored.py:421: FutureWarning: The behavior of DataFrame
                             concatenation with empty or all-NA entries is deprecated. In a future
                             version, this will no longer exclude empty or all-NA columns when
                             determining the result dtypes. To retain the old behavior, exclude the
                             relevant entries before the concat operation.
                               pd.concat(all_schedules)

In [4]:
epl_schedule.to_csv('prem_2026.csv')

In [5]:
epl = pd.read_csv('prem_2026.csv')

home_manutd = epl[epl['home_team'] == 'Manchester United']
away_manutd = epl[epl['away_team'] == 'Manchester United']

manutd = pd.concat([home_manutd, away_manutd])

manutd

,league,season,game,stage_id,game_id,status,start_time,home_team_id,home_team,home_yellow_cards,...,period,extra_result_field,home_extratime_score,away_extratime_score,home_penalty_score,away_penalty_score,started_at_utc,first_half_ended_at_utc,second_half_started_at_utc,stage
17,ENG-Premier League,2627,2026-08-30 Manchester United-Ipswich,25544,1983562,1,2026-08-30T16:30:00,32,Manchester United,0,...,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
38,ENG-Premier League,2627,2026-09-13 Manchester United-Manchester City,25544,1983566,1,2026-09-13T16:30:00,32,Manchester United,0,...,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
54,ENG-Premier League,2627,2026-10-10 Manchester United-Tottenham,25544,1983604,1,2026-10-10T17:30:00,32,Manchester United,0,...,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
78,ENG-Premier League,2627,2026-10-25 Manchester United-Bournemouth,25544,1983624,1,2026-10-25T14:00:00,32,Manchester United,0,...,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
97,ENG-Premier League,2627,2026-11-07 Manchester United-Aston Villa,25544,1983850,1,2026-11-07T15:00:00,32,Manchester United,0,...,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
117,ENG-Premier League,2627,2026-11-28 Manchester United-Brentford,25544,1983831,1,2026-11-28T15:00:00,32,Manchester United,0,...,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
136,ENG-Premier League,2627,2026-12-05 Manchester United-Coventry,25544,1983647,1,2026-12-05T15:00:00,32,Manchester United,0,...,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
167,ENG-Premier League,2627,2026-12-26 Manchester United-Nottingham Forest,25544,1983645,1,2026-12-26T15:00:00,32,Manchester United,0,...,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
177,ENG-Premier League,2627,2026-12-30 Manchester United-Sunderland,25544,1983681,1,2026-12-30T20:00:00,32,Manchester United,0,...,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
197,ENG-Premier League,2627,2027-01-06 Manchester United-Newcastle,25544,1983739,1,2027-01-06T20:00:00,32,Manchester United,0,...,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
217,ENG-Premier League,2627,2027-01-23 Manchester United-Liverpool,25544,1983680,1,2027-01-23T15:00:00,32,Manchester United,0,...,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
237,ENG-Premier League,2627,2027-02-06 Manchester United-Chelsea,25544,1983754,1,2027-02-06T15:00:00,32,Manchester United,0,...,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
247,ENG-Premier League,2627,2027-02-10 Manchester United-Brighton,25544,1983774,1,2027-02-10T20:00:00,32,Manchester United,0,...,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
267,ENG-Premier League,2627,2027-02-27 Manchester United-Arsenal,25544,1983742,1,2027-02-27T15:00:00,32,Manchester United,0,...,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
287,ENG-Premier League,2627,2027-03-13 Manchester United-Everton,25544,1983775,1,2027-03-13T15:00:00,32,Manchester United,0,...,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
307,ENG-Premier League,2627,2027-04-10 Manchester United-Hull,25544,1983809,1,2027-04-10T15:00:00,32,Manchester United,0,...,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
326,ENG-Premier League,2627,2027-04-24 Manchester United-Crystal Palace,25544,1983872,1,2027-04-24T15:00:00,32,Manchester United,0,...,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
358,ENG-Premier League,2627,2027-05-15 Manchester United-Leeds,25544,1983915,1,2027-05-15T15:00:00,32,Manchester United,0,...,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
378,ENG-Premier League,2627,2027-05-30 Manchester United-Fulham,25544,1983902,1,2027-05-30T16:00:00,32,Manchester United,0,...,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,ENG-Premier League,2627,2026-08-22 Hull-Manchester United,25544,1983548,6,2026-08-22T12:30:00,214,Hull,2,...,7,NaN,NaN,NaN,NaN,NaN,2026-08-22T11:30:07Z,2026-08-22T12:17:13Z,2026-08-22T12:33:07Z,NaN
29,ENG-Premier League,2627,2026-09-06 Everton-Manchester United,25544,1983574,1,2026-09-06T14:00:00,31,Everton,0,...,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
49,ENG-Premier League,2627,2026-09-20 Fulham-Manchester United,25544,1983579,1,2026-09-20T16:30:00,170,Fulham,0,...,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
67,ENG-Premier League,2627,2026-10-18 Leeds-Manchester United,25544,1983611,1,2026-10-18T14:00:00,19,Leeds,0,...,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
82,ENG-Premier League,2627,2026-10-31 Chelsea-Manchester United,25544,1983629,1,2026-10-31T12:30:00,15,Chelsea,0,...,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
106,ENG-Premier League,2627,2026-11-21 Liverpool-Manchester United,25544,1983820,1,2026-11-21T15:00:00,26,Liverpool,0,...,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
128,ENG-Premier League,2627,2026-12-02 Newcastle-Manchester United,25544,1983854,1,2026-12-02T20:00:00,23,Newcastle,0,...,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
143,ENG-Premier League,2627,2026-12-12 Crystal Palace-Manchester United,25544,1983670,1,2026-12-12T15:00:00,162,Crystal Palace,0,...,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
150,ENG-Premier League,2627,2026-12-19 Arsenal-Manchester United,25544,1983694,1,2026-12-19T15:00:00,13,Arsenal,0,...,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
183,ENG-Premier League,2627,2027-01-02 Brighton-Manchester United,25544,1983699,1,2027-01-02T15:00:00,211,Brighton,0,...,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
200,ENG-Premier League,2627,2027-01-16 Aston Villa-Manchester United,25544,1983641,1,2027-01-16T15:00:00,24,Aston Villa,0,...,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
222,ENG-Premier League,2627,2027-01-30 Brentford-Manchester United,25544,1983695,1,2027-01-30T15:00:00,189,Brentford,0,...,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
258,ENG-Premier League,2627,2027-02-20 Nottingham Forest-Manchester United,25544,1983798,1,2027-02-20T15:00:00,174,Nottingham Forest,0,...,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
279,ENG-Premier League,2627,2027-03-03 Sunderland-Manchester United,25544,1983759,1,2027-03-03T20:00:00,16,Sunderland,0,...,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
297,ENG-Premier League,2627,2027-03-20 Manchester City-Manchester United,25544,1983794,1,2027-03-20T15:00:00,167,Manchester City,0,...,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
316,ENG-Premier League,2627,2027-04-17 Ipswich-Manchester United,25544,1983862,1,2027-04-17T15:00:00,165,Ipswich,0,...,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
332,ENG-Premier League,2627,2027-05-01 Coventry-Manchester United,25544,1983878,1,2027-05-01T15:00:00,17,Coventry,0,...,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
340,ENG-Premier League,2627,2027-05-08 Bournemouth-Manchester United,25544,1983886,1,2027-05-08T15:00:00,183,Bournemouth,0,...,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
369,ENG-Premier League,2627,2027-05-23 Tottenham-Manchester United,25544,1983889,1,2027-05-23T15:00:00,30,Tottenham,0,...,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [6]:
list = manutd['game_id'].to_list()
for i in range(len(list)):
    print(list[i])

1983562
1983566
1983604
1983624
1983850
1983831
1983647
1983645
1983681
1983739
1983680
1983754
1983774
1983742
1983775
1983809
1983872
1983915
1983902
1983548
1983574
1983579
1983611
1983629
1983820
1983854
1983670
1983694
1983699
1983641
1983695
1983798
1983759
1983794
1983862
1983878
1983886
1983889

In [7]:
utd_game_list = []

for i in range(5):
    game = ws.read_events(match_id = list[i])
    utd_game_list.append(game)

[08/23/26 16:43:47] INFO     Retrieving calendar for ENG-Premier League 2627                       ]8;id=3503434;file:///home/caff/Documents/footy_analysis/.venv/lib/python3.12/site-packages/soccerdata/whoscored.py\whoscored.py]8;;\:]8;id=3503435;file:///home/caff/Documents/footy_analysis/.venv/lib/python3.12/site-packages/soccerdata/whoscored.py#366\366]8;;\

[08/23/26 16:44:00] INFO     [1/10] Retrieving fixtures for ENG-Premier League 2627                ]8;id=3503440;file:///home/caff/Documents/footy_analysis/.venv/lib/python3.12/site-packages/soccerdata/whoscored.py\whoscored.py]8;;\:]8;id=3503441;file:///home/caff/Documents/footy_analysis/.venv/lib/python3.12/site-packages/soccerdata/whoscored.py#397\397]8;;\

[08/23/26 16:44:11] INFO     [2/10] Retrieving fixtures for ENG-Premier League 2627                ]8;id=3503446;file:///home/caff/Documents/footy_analysis/.venv/lib/python3.12/site-packages/soccerdata/whoscored.py\whoscored.py]8;;\:]8;id=3503447;file:///home/caff/Documents/footy_analysis/.venv/lib/python3.12/site-packages/soccerdata/whoscored.py#397\397]8;;\

[08/23/26 16:44:24] INFO     [3/10] Retrieving fixtures for ENG-Premier League 2627                ]8;id=3503452;file:///home/caff/Documents/footy_analysis/.venv/lib/python3.12/site-packages/soccerdata/whoscored.py\whoscored.py]8;;\:]8;id=3503453;file:///home/caff/Documents/footy_analysis/.venv/lib/python3.12/site-packages/soccerdata/whoscored.py#397\397]8;;\

[08/23/26 16:44:33] INFO     [4/10] Retrieving fixtures for ENG-Premier League 2627                ]8;id=3503458;file:///home/caff/Documents/footy_analysis/.venv/lib/python3.12/site-packages/soccerdata/whoscored.py\whoscored.py]8;;\:]8;id=3503459;file:///home/caff/Documents/footy_analysis/.venv/lib/python3.12/site-packages/soccerdata/whoscored.py#397\397]8;;\

[08/23/26 16:44:44] INFO     [5/10] Retrieving fixtures for ENG-Premier League 2627                ]8;id=3503464;file:///home/caff/Documents/footy_analysis/.venv/lib/python3.12/site-packages/soccerdata/whoscored.py\whoscored.py]8;;\:]8;id=3503465;file:///home/caff/Documents/footy_analysis/.venv/lib/python3.12/site-packages/soccerdata/whoscored.py#397\397]8;;\

[08/23/26 16:44:54] INFO     [6/10] Retrieving fixtures for ENG-Premier League 2627                ]8;id=3503470;file:///home/caff/Documents/footy_analysis/.venv/lib/python3.12/site-packages/soccerdata/whoscored.py\whoscored.py]8;;\:]8;id=3503471;file:///home/caff/Documents/footy_analysis/.venv/lib/python3.12/site-packages/soccerdata/whoscored.py#397\397]8;;\

[08/23/26 16:45:06] INFO     [7/10] Retrieving fixtures for ENG-Premier League 2627                ]8;id=3503476;file:///home/caff/Documents/footy_analysis/.venv/lib/python3.12/site-packages/soccerdata/whoscored.py\whoscored.py]8;;\:]8;id=3503477;file:///home/caff/Documents/footy_analysis/.venv/lib/python3.12/site-packages/soccerdata/whoscored.py#397\397]8;;\

[08/23/26 16:45:16] INFO     [8/10] Retrieving fixtures for ENG-Premier League 2627                ]8;id=3503482;file:///home/caff/Documents/footy_analysis/.venv/lib/python3.12/site-packages/soccerdata/whoscored.py\whoscored.py]8;;\:]8;id=3503483;file:///home/caff/Documents/footy_analysis/.venv/lib/python3.12/site-packages/soccerdata/whoscored.py#397\397]8;;\

[08/23/26 16:45:28] INFO     [9/10] Retrieving fixtures for ENG-Premier League 2627                ]8;id=3503488;file:///home/caff/Documents/footy_analysis/.venv/lib/python3.12/site-packages/soccerdata/whoscored.py\whoscored.py]8;;\:]8;id=3503489;file:///home/caff/Documents/footy_analysis/.venv/lib/python3.12/site-packages/soccerdata/whoscored.py#397\397]8;;\

[08/23/26 16:45:39] INFO     [10/10] Retrieving fixtures for ENG-Premier League 2627               ]8;id=3503494;file:///home/caff/Documents/footy_analysis/.venv/lib/python3.12/site-packages/soccerdata/whoscored.py\whoscored.py]8;;\:]8;id=3503495;file:///home/caff/Documents/footy_analysis/.venv/lib/python3.12/site-packages/soccerdata/whoscored.py#397\397]8;;\

[08/23/26 16:45:48] WARNING  /home/caff/Documents/footy_analysis/.venv/lib/python3.12/site-packages ]8;id=3503500;file:///home/caff/.pyenv/versions/3.12.13/lib/python3.12/warnings.py\warnings.py]8;;\:]8;id=3503501;file:///home/caff/.pyenv/versions/3.12.13/lib/python3.12/warnings.py#112\112]8;;\
                             /soccerdata/whoscored.py:421: FutureWarning: The behavior of DataFrame
                             concatenation with empty or all-NA entries is deprecated. In a future
                             version, this will no longer exclude empty or all-NA columns when
                             determining the result dtypes. To retain the old behavior, exclude the
                             relevant entries before the concat operation.
                               pd.concat(all_schedules)

                    INFO     [1/1] Retrieving game with id=1983562                                 ]8;id=3503507;file:///home/caff/Documents/footy_analysis/.venv/lib/python3.12/site-packages/soccerdata/whoscored.py\whoscored.py]8;;\:]8;id=3503508;file:///home/caff/Documents/footy_analysis/.venv/lib/python3.12/site-packages/soccerdata/whoscored.py#689\689]8;;\

[08/23/26 16:46:04] WARNING  No events found for game 1983562                                      ]8;id=3503514;file:///home/caff/Documents/footy_analysis/.venv/lib/python3.12/site-packages/soccerdata/whoscored.py\whoscored.py]8;;\:]8;id=3503515;file:///home/caff/Documents/footy_analysis/.venv/lib/python3.12/site-packages/soccerdata/whoscored.py#763\763]8;;\

[08/23/26 16:46:15] INFO     Retrieving calendar for ENG-Premier League 2627                       ]8;id=3503520;file:///home/caff/Documents/footy_analysis/.venv/lib/python3.12/site-packages/soccerdata/whoscored.py\whoscored.py]8;;\:]8;id=3503521;file:///home/caff/Documents/footy_analysis/.venv/lib/python3.12/site-packages/soccerdata/whoscored.py#366\366]8;;\

[08/23/26 16:50:16] INFO     [1/10] Retrieving fixtures for ENG-Premier League 2627                ]8;id=3503526;file:///home/caff/Documents/footy_analysis/.venv/lib/python3.12/site-packages/soccerdata/whoscored.py\whoscored.py]8;;\:]8;id=3503527;file:///home/caff/Documents/footy_analysis/.venv/lib/python3.12/site-packages/soccerdata/whoscored.py#397\397]8;;\

[08/23/26 16:50:26] INFO     [2/10] Retrieving fixtures for ENG-Premier League 2627                ]8;id=3503532;file:///home/caff/Documents/footy_analysis/.venv/lib/python3.12/site-packages/soccerdata/whoscored.py\whoscored.py]8;;\:]8;id=3503533;file:///home/caff/Documents/footy_analysis/.venv/lib/python3.12/site-packages/soccerdata/whoscored.py#397\397]8;;\

[08/23/26 16:50:37] INFO     [3/10] Retrieving fixtures for ENG-Premier League 2627                ]8;id=3503538;file:///home/caff/Documents/footy_analysis/.venv/lib/python3.12/site-packages/soccerdata/whoscored.py\whoscored.py]8;;\:]8;id=3503539;file:///home/caff/Documents/footy_analysis/.venv/lib/python3.12/site-packages/soccerdata/whoscored.py#397\397]8;;\

[08/23/26 16:50:51] INFO     [4/10] Retrieving fixtures for ENG-Premier League 2627                ]8;id=3503544;file:///home/caff/Documents/footy_analysis/.venv/lib/python3.12/site-packages/soccerdata/whoscored.py\whoscored.py]8;;\:]8;id=3503545;file:///home/caff/Documents/footy_analysis/.venv/lib/python3.12/site-packages/soccerdata/whoscored.py#397\397]8;;\

[08/23/26 16:51:03] INFO     [5/10] Retrieving fixtures for ENG-Premier League 2627                ]8;id=3503550;file:///home/caff/Documents/footy_analysis/.venv/lib/python3.12/site-packages/soccerdata/whoscored.py\whoscored.py]8;;\:]8;id=3503551;file:///home/caff/Documents/footy_analysis/.venv/lib/python3.12/site-packages/soccerdata/whoscored.py#397\397]8;;\

[08/23/26 16:51:15] INFO     [6/10] Retrieving fixtures for ENG-Premier League 2627                ]8;id=3503556;file:///home/caff/Documents/footy_analysis/.venv/lib/python3.12/site-packages/soccerdata/whoscored.py\whoscored.py]8;;\:]8;id=3503557;file:///home/caff/Documents/footy_analysis/.venv/lib/python3.12/site-packages/soccerdata/whoscored.py#397\397]8;;\

[08/23/26 16:51:25] INFO     [7/10] Retrieving fixtures for ENG-Premier League 2627                ]8;id=3503562;file:///home/caff/Documents/footy_analysis/.venv/lib/python3.12/site-packages/soccerdata/whoscored.py\whoscored.py]8;;\:]8;id=3503563;file:///home/caff/Documents/footy_analysis/.venv/lib/python3.12/site-packages/soccerdata/whoscored.py#397\397]8;;\

[08/23/26 16:51:36] INFO     [8/10] Retrieving fixtures for ENG-Premier League 2627                ]8;id=3503568;file:///home/caff/Documents/footy_analysis/.venv/lib/python3.12/site-packages/soccerdata/whoscored.py\whoscored.py]8;;\:]8;id=3503569;file:///home/caff/Documents/footy_analysis/.venv/lib/python3.12/site-packages/soccerdata/whoscored.py#397\397]8;;\

[08/23/26 16:51:47] INFO     [9/10] Retrieving fixtures for ENG-Premier League 2627                ]8;id=3503574;file:///home/caff/Documents/footy_analysis/.venv/lib/python3.12/site-packages/soccerdata/whoscored.py\whoscored.py]8;;\:]8;id=3503575;file:///home/caff/Documents/footy_analysis/.venv/lib/python3.12/site-packages/soccerdata/whoscored.py#397\397]8;;\

[08/23/26 16:51:55] INFO     [10/10] Retrieving fixtures for ENG-Premier League 2627               ]8;id=3503580;file:///home/caff/Documents/footy_analysis/.venv/lib/python3.12/site-packages/soccerdata/whoscored.py\whoscored.py]8;;\:]8;id=3503581;file:///home/caff/Documents/footy_analysis/.venv/lib/python3.12/site-packages/soccerdata/whoscored.py#397\397]8;;\

[08/23/26 16:52:06] WARNING  /home/caff/Documents/footy_analysis/.venv/lib/python3.12/site-packages ]8;id=3503586;file:///home/caff/.pyenv/versions/3.12.13/lib/python3.12/warnings.py\warnings.py]8;;\:]8;id=3503587;file:///home/caff/.pyenv/versions/3.12.13/lib/python3.12/warnings.py#112\112]8;;\
                             /soccerdata/whoscored.py:421: FutureWarning: The behavior of DataFrame
                             concatenation with empty or all-NA entries is deprecated. In a future
                             version, this will no longer exclude empty or all-NA columns when
                             determining the result dtypes. To retain the old behavior, exclude the
                             relevant entries before the concat operation.
                               pd.concat(all_schedules)

                    INFO     [1/1] Retrieving game with id=1983566                                 ]8;id=3503592;file:///home/caff/Documents/footy_analysis/.venv/lib/python3.12/site-packages/soccerdata/whoscored.py\whoscored.py]8;;\:]8;id=3503593;file:///home/caff/Documents/footy_analysis/.venv/lib/python3.12/site-packages/soccerdata/whoscored.py#689\689]8;;\

[08/23/26 16:52:17] WARNING  No events found for game 1983566                                      ]8;id=3503598;file:///home/caff/Documents/footy_analysis/.venv/lib/python3.12/site-packages/soccerdata/whoscored.py\whoscored.py]8;;\:]8;id=3503599;file:///home/caff/Documents/footy_analysis/.venv/lib/python3.12/site-packages/soccerdata/whoscored.py#763\763]8;;\

[08/23/26 16:52:33] INFO     Retrieving calendar for ENG-Premier League 2627                       ]8;id=3503604;file:///home/caff/Documents/footy_analysis/.venv/lib/python3.12/site-packages/soccerdata/whoscored.py\whoscored.py]8;;\:]8;id=3503605;file:///home/caff/Documents/footy_analysis/.venv/lib/python3.12/site-packages/soccerdata/whoscored.py#366\366]8;;\

[08/23/26 16:52:41] INFO     [1/10] Retrieving fixtures for ENG-Premier League 2627                ]8;id=3503610;file:///home/caff/Documents/footy_analysis/.venv/lib/python3.12/site-packages/soccerdata/whoscored.py\whoscored.py]8;;\:]8;id=3503611;file:///home/caff/Documents/footy_analysis/.venv/lib/python3.12/site-packages/soccerdata/whoscored.py#397\397]8;;\

[08/23/26 16:52:51] INFO     [2/10] Retrieving fixtures for ENG-Premier League 2627                ]8;id=3503616;file:///home/caff/Documents/footy_analysis/.venv/lib/python3.12/site-packages/soccerdata/whoscored.py\whoscored.py]8;;\:]8;id=3503617;file:///home/caff/Documents/footy_analysis/.venv/lib/python3.12/site-packages/soccerdata/whoscored.py#397\397]8;;\

[08/23/26 16:52:59] INFO     [3/10] Retrieving fixtures for ENG-Premier League 2627                ]8;id=3503622;file:///home/caff/Documents/footy_analysis/.venv/lib/python3.12/site-packages/soccerdata/whoscored.py\whoscored.py]8;;\:]8;id=3503623;file:///home/caff/Documents/footy_analysis/.venv/lib/python3.12/site-packages/soccerdata/whoscored.py#397\397]8;;\

[08/23/26 16:53:10] INFO     [4/10] Retrieving fixtures for ENG-Premier League 2627                ]8;id=3503628;file:///home/caff/Documents/footy_analysis/.venv/lib/python3.12/site-packages/soccerdata/whoscored.py\whoscored.py]8;;\:]8;id=3503629;file:///home/caff/Documents/footy_analysis/.venv/lib/python3.12/site-packages/soccerdata/whoscored.py#397\397]8;;\

[08/23/26 16:53:22] INFO     [5/10] Retrieving fixtures for ENG-Premier League 2627                ]8;id=3503634;file:///home/caff/Documents/footy_analysis/.venv/lib/python3.12/site-packages/soccerdata/whoscored.py\whoscored.py]8;;\:]8;id=3503635;file:///home/caff/Documents/footy_analysis/.venv/lib/python3.12/site-packages/soccerdata/whoscored.py#397\397]8;;\

[08/23/26 16:53:32] INFO     [6/10] Retrieving fixtures for ENG-Premier League 2627                ]8;id=3503640;file:///home/caff/Documents/footy_analysis/.venv/lib/python3.12/site-packages/soccerdata/whoscored.py\whoscored.py]8;;\:]8;id=3503641;file:///home/caff/Documents/footy_analysis/.venv/lib/python3.12/site-packages/soccerdata/whoscored.py#397\397]8;;\

[08/23/26 16:53:43] INFO     [7/10] Retrieving fixtures for ENG-Premier League 2627                ]8;id=3503646;file:///home/caff/Documents/footy_analysis/.venv/lib/python3.12/site-packages/soccerdata/whoscored.py\whoscored.py]8;;\:]8;id=3503647;file:///home/caff/Documents/footy_analysis/.venv/lib/python3.12/site-packages/soccerdata/whoscored.py#397\397]8;;\

[08/23/26 16:53:52] INFO     [8/10] Retrieving fixtures for ENG-Premier League 2627                ]8;id=3503652;file:///home/caff/Documents/footy_analysis/.venv/lib/python3.12/site-packages/soccerdata/whoscored.py\whoscored.py]8;;\:]8;id=3503653;file:///home/caff/Documents/footy_analysis/.venv/lib/python3.12/site-packages/soccerdata/whoscored.py#397\397]8;;\

[08/23/26 16:54:04] INFO     [9/10] Retrieving fixtures for ENG-Premier League 2627                ]8;id=3503658;file:///home/caff/Documents/footy_analysis/.venv/lib/python3.12/site-packages/soccerdata/whoscored.py\whoscored.py]8;;\:]8;id=3503659;file:///home/caff/Documents/footy_analysis/.venv/lib/python3.12/site-packages/soccerdata/whoscored.py#397\397]8;;\

[08/23/26 16:54:14] INFO     [10/10] Retrieving fixtures for ENG-Premier League 2627               ]8;id=3503664;file:///home/caff/Documents/footy_analysis/.venv/lib/python3.12/site-packages/soccerdata/whoscored.py\whoscored.py]8;;\:]8;id=3503665;file:///home/caff/Documents/footy_analysis/.venv/lib/python3.12/site-packages/soccerdata/whoscored.py#397\397]8;;\

[08/23/26 16:54:22] WARNING  /home/caff/Documents/footy_analysis/.venv/lib/python3.12/site-packages ]8;id=3503670;file:///home/caff/.pyenv/versions/3.12.13/lib/python3.12/warnings.py\warnings.py]8;;\:]8;id=3503671;file:///home/caff/.pyenv/versions/3.12.13/lib/python3.12/warnings.py#112\112]8;;\
                             /soccerdata/whoscored.py:421: FutureWarning: The behavior of DataFrame
                             concatenation with empty or all-NA entries is deprecated. In a future
                             version, this will no longer exclude empty or all-NA columns when
                             determining the result dtypes. To retain the old behavior, exclude the
                             relevant entries before the concat operation.
                               pd.concat(all_schedules)

                    INFO     [1/1] Retrieving game with id=1983604                                 ]8;id=3503676;file:///home/caff/Documents/footy_analysis/.venv/lib/python3.12/site-packages/soccerdata/whoscored.py\whoscored.py]8;;\:]8;id=3503677;file:///home/caff/Documents/footy_analysis/.venv/lib/python3.12/site-packages/soccerdata/whoscored.py#689\689]8;;\

[08/23/26 16:54:35] WARNING  No events found for game 1983604                                      ]8;id=3503682;file:///home/caff/Documents/footy_analysis/.venv/lib/python3.12/site-packages/soccerdata/whoscored.py\whoscored.py]8;;\:]8;id=3503683;file:///home/caff/Documents/footy_analysis/.venv/lib/python3.12/site-packages/soccerdata/whoscored.py#763\763]8;;\

[08/23/26 16:54:45] INFO     Retrieving calendar for ENG-Premier League 2627                       ]8;id=3503688;file:///home/caff/Documents/footy_analysis/.venv/lib/python3.12/site-packages/soccerdata/whoscored.py\whoscored.py]8;;\:]8;id=3503689;file:///home/caff/Documents/footy_analysis/.venv/lib/python3.12/site-packages/soccerdata/whoscored.py#366\366]8;;\

[08/23/26 16:54:56] INFO     [1/10] Retrieving fixtures for ENG-Premier League 2627                ]8;id=3503694;file:///home/caff/Documents/footy_analysis/.venv/lib/python3.12/site-packages/soccerdata/whoscored.py\whoscored.py]8;;\:]8;id=3503695;file:///home/caff/Documents/footy_analysis/.venv/lib/python3.12/site-packages/soccerdata/whoscored.py#397\397]8;;\

[08/23/26 16:55:08] INFO     [2/10] Retrieving fixtures for ENG-Premier League 2627                ]8;id=3503700;file:///home/caff/Documents/footy_analysis/.venv/lib/python3.12/site-packages/soccerdata/whoscored.py\whoscored.py]8;;\:]8;id=3503701;file:///home/caff/Documents/footy_analysis/.venv/lib/python3.12/site-packages/soccerdata/whoscored.py#397\397]8;;\

[08/23/26 16:55:19] INFO     [3/10] Retrieving fixtures for ENG-Premier League 2627                ]8;id=3503706;file:///home/caff/Documents/footy_analysis/.venv/lib/python3.12/site-packages/soccerdata/whoscored.py\whoscored.py]8;;\:]8;id=3503707;file:///home/caff/Documents/footy_analysis/.venv/lib/python3.12/site-packages/soccerdata/whoscored.py#397\397]8;;\

[08/23/26 16:55:31] INFO     [4/10] Retrieving fixtures for ENG-Premier League 2627                ]8;id=3503712;file:///home/caff/Documents/footy_analysis/.venv/lib/python3.12/site-packages/soccerdata/whoscored.py\whoscored.py]8;;\:]8;id=3503713;file:///home/caff/Documents/footy_analysis/.venv/lib/python3.12/site-packages/soccerdata/whoscored.py#397\397]8;;\

[08/23/26 16:55:45] INFO     [5/10] Retrieving fixtures for ENG-Premier League 2627                ]8;id=3503718;file:///home/caff/Documents/footy_analysis/.venv/lib/python3.12/site-packages/soccerdata/whoscored.py\whoscored.py]8;;\:]8;id=3503719;file:///home/caff/Documents/footy_analysis/.venv/lib/python3.12/site-packages/soccerdata/whoscored.py#397\397]8;;\

[08/23/26 16:55:55] INFO     [6/10] Retrieving fixtures for ENG-Premier League 2627                ]8;id=3503724;file:///home/caff/Documents/footy_analysis/.venv/lib/python3.12/site-packages/soccerdata/whoscored.py\whoscored.py]8;;\:]8;id=3503725;file:///home/caff/Documents/footy_analysis/.venv/lib/python3.12/site-packages/soccerdata/whoscored.py#397\397]8;;\

[08/23/26 16:56:04] INFO     [7/10] Retrieving fixtures for ENG-Premier League 2627                ]8;id=3503730;file:///home/caff/Documents/footy_analysis/.venv/lib/python3.12/site-packages/soccerdata/whoscored.py\whoscored.py]8;;\:]8;id=3503731;file:///home/caff/Documents/footy_analysis/.venv/lib/python3.12/site-packages/soccerdata/whoscored.py#397\397]8;;\

[08/23/26 16:56:12] INFO     [8/10] Retrieving fixtures for ENG-Premier League 2627                ]8;id=3503736;file:///home/caff/Documents/footy_analysis/.venv/lib/python3.12/site-packages/soccerdata/whoscored.py\whoscored.py]8;;\:]8;id=3503737;file:///home/caff/Documents/footy_analysis/.venv/lib/python3.12/site-packages/soccerdata/whoscored.py#397\397]8;;\

[08/23/26 16:56:22] INFO     [9/10] Retrieving fixtures for ENG-Premier League 2627                ]8;id=3503742;file:///home/caff/Documents/footy_analysis/.venv/lib/python3.12/site-packages/soccerdata/whoscored.py\whoscored.py]8;;\:]8;id=3503743;file:///home/caff/Documents/footy_analysis/.venv/lib/python3.12/site-packages/soccerdata/whoscored.py#397\397]8;;\

[08/23/26 16:56:33] INFO     [10/10] Retrieving fixtures for ENG-Premier League 2627               ]8;id=3503748;file:///home/caff/Documents/footy_analysis/.venv/lib/python3.12/site-packages/soccerdata/whoscored.py\whoscored.py]8;;\:]8;id=3503749;file:///home/caff/Documents/footy_analysis/.venv/lib/python3.12/site-packages/soccerdata/whoscored.py#397\397]8;;\

[08/23/26 16:56:42] WARNING  /home/caff/Documents/footy_analysis/.venv/lib/python3.12/site-packages ]8;id=3503754;file:///home/caff/.pyenv/versions/3.12.13/lib/python3.12/warnings.py\warnings.py]8;;\:]8;id=3503755;file:///home/caff/.pyenv/versions/3.12.13/lib/python3.12/warnings.py#112\112]8;;\
                             /soccerdata/whoscored.py:421: FutureWarning: The behavior of DataFrame
                             concatenation with empty or all-NA entries is deprecated. In a future
                             version, this will no longer exclude empty or all-NA columns when
                             determining the result dtypes. To retain the old behavior, exclude the
                             relevant entries before the concat operation.
                               pd.concat(all_schedules)

                    INFO     [1/1] Retrieving game with id=1983624                                 ]8;id=3503760;file:///home/caff/Documents/footy_analysis/.venv/lib/python3.12/site-packages/soccerdata/whoscored.py\whoscored.py]8;;\:]8;id=3503761;file:///home/caff/Documents/footy_analysis/.venv/lib/python3.12/site-packages/soccerdata/whoscored.py#689\689]8;;\

[08/23/26 16:57:04] WARNING  No events found for game 1983624                                      ]8;id=3503766;file:///home/caff/Documents/footy_analysis/.venv/lib/python3.12/site-packages/soccerdata/whoscored.py\whoscored.py]8;;\:]8;id=3503767;file:///home/caff/Documents/footy_analysis/.venv/lib/python3.12/site-packages/soccerdata/whoscored.py#763\763]8;;\

[08/23/26 16:57:12] INFO     Retrieving calendar for ENG-Premier League 2627                       ]8;id=3503772;file:///home/caff/Documents/footy_analysis/.venv/lib/python3.12/site-packages/soccerdata/whoscored.py\whoscored.py]8;;\:]8;id=3503773;file:///home/caff/Documents/footy_analysis/.venv/lib/python3.12/site-packages/soccerdata/whoscored.py#366\366]8;;\

[08/23/26 16:57:22] INFO     [1/10] Retrieving fixtures for ENG-Premier League 2627                ]8;id=3503778;file:///home/caff/Documents/footy_analysis/.venv/lib/python3.12/site-packages/soccerdata/whoscored.py\whoscored.py]8;;\:]8;id=3503779;file:///home/caff/Documents/footy_analysis/.venv/lib/python3.12/site-packages/soccerdata/whoscored.py#397\397]8;;\

[08/23/26 16:57:31] INFO     [2/10] Retrieving fixtures for ENG-Premier League 2627                ]8;id=3503784;file:///home/caff/Documents/footy_analysis/.venv/lib/python3.12/site-packages/soccerdata/whoscored.py\whoscored.py]8;;\:]8;id=3503785;file:///home/caff/Documents/footy_analysis/.venv/lib/python3.12/site-packages/soccerdata/whoscored.py#397\397]8;;\

[08/23/26 16:57:41] INFO     [3/10] Retrieving fixtures for ENG-Premier League 2627                ]8;id=3503790;file:///home/caff/Documents/footy_analysis/.venv/lib/python3.12/site-packages/soccerdata/whoscored.py\whoscored.py]8;;\:]8;id=3503791;file:///home/caff/Documents/footy_analysis/.venv/lib/python3.12/site-packages/soccerdata/whoscored.py#397\397]8;;\

[08/23/26 16:57:49] INFO     [4/10] Retrieving fixtures for ENG-Premier League 2627                ]8;id=3503796;file:///home/caff/Documents/footy_analysis/.venv/lib/python3.12/site-packages/soccerdata/whoscored.py\whoscored.py]8;;\:]8;id=3503797;file:///home/caff/Documents/footy_analysis/.venv/lib/python3.12/site-packages/soccerdata/whoscored.py#397\397]8;;\

[08/23/26 16:58:03] INFO     [5/10] Retrieving fixtures for ENG-Premier League 2627                ]8;id=3503802;file:///home/caff/Documents/footy_analysis/.venv/lib/python3.12/site-packages/soccerdata/whoscored.py\whoscored.py]8;;\:]8;id=3503803;file:///home/caff/Documents/footy_analysis/.venv/lib/python3.12/site-packages/soccerdata/whoscored.py#397\397]8;;\

[08/23/26 16:58:12] INFO     [6/10] Retrieving fixtures for ENG-Premier League 2627                ]8;id=3503808;file:///home/caff/Documents/footy_analysis/.venv/lib/python3.12/site-packages/soccerdata/whoscored.py\whoscored.py]8;;\:]8;id=3503809;file:///home/caff/Documents/footy_analysis/.venv/lib/python3.12/site-packages/soccerdata/whoscored.py#397\397]8;;\

[08/23/26 16:58:23] INFO     [7/10] Retrieving fixtures for ENG-Premier League 2627                ]8;id=3503814;file:///home/caff/Documents/footy_analysis/.venv/lib/python3.12/site-packages/soccerdata/whoscored.py\whoscored.py]8;;\:]8;id=3503815;file:///home/caff/Documents/footy_analysis/.venv/lib/python3.12/site-packages/soccerdata/whoscored.py#397\397]8;;\

[08/23/26 16:58:35] INFO     [8/10] Retrieving fixtures for ENG-Premier League 2627                ]8;id=3503820;file:///home/caff/Documents/footy_analysis/.venv/lib/python3.12/site-packages/soccerdata/whoscored.py\whoscored.py]8;;\:]8;id=3503821;file:///home/caff/Documents/footy_analysis/.venv/lib/python3.12/site-packages/soccerdata/whoscored.py#397\397]8;;\

[08/23/26 16:58:48] INFO     [9/10] Retrieving fixtures for ENG-Premier League 2627                ]8;id=3503826;file:///home/caff/Documents/footy_analysis/.venv/lib/python3.12/site-packages/soccerdata/whoscored.py\whoscored.py]8;;\:]8;id=3503827;file:///home/caff/Documents/footy_analysis/.venv/lib/python3.12/site-packages/soccerdata/whoscored.py#397\397]8;;\

[08/23/26 16:58:58] INFO     [10/10] Retrieving fixtures for ENG-Premier League 2627               ]8;id=3503832;file:///home/caff/Documents/footy_analysis/.venv/lib/python3.12/site-packages/soccerdata/whoscored.py\whoscored.py]8;;\:]8;id=3503833;file:///home/caff/Documents/footy_analysis/.venv/lib/python3.12/site-packages/soccerdata/whoscored.py#397\397]8;;\

[08/23/26 16:59:09] WARNING  /home/caff/Documents/footy_analysis/.venv/lib/python3.12/site-packages ]8;id=3503838;file:///home/caff/.pyenv/versions/3.12.13/lib/python3.12/warnings.py\warnings.py]8;;\:]8;id=3503839;file:///home/caff/.pyenv/versions/3.12.13/lib/python3.12/warnings.py#112\112]8;;\
                             /soccerdata/whoscored.py:421: FutureWarning: The behavior of DataFrame
                             concatenation with empty or all-NA entries is deprecated. In a future
                             version, this will no longer exclude empty or all-NA columns when
                             determining the result dtypes. To retain the old behavior, exclude the
                             relevant entries before the concat operation.
                               pd.concat(all_schedules)

                    INFO     [1/1] Retrieving game with id=1983850                                 ]8;id=3503844;file:///home/caff/Documents/footy_analysis/.venv/lib/python3.12/site-packages/soccerdata/whoscored.py\whoscored.py]8;;\:]8;id=3503845;file:///home/caff/Documents/footy_analysis/.venv/lib/python3.12/site-packages/soccerdata/whoscored.py#689\689]8;;\

[08/23/26 16:59:32] WARNING  No events found for game 1983850                                      ]8;id=3503850;file:///home/caff/Documents/footy_analysis/.venv/lib/python3.12/site-packages/soccerdata/whoscored.py\whoscored.py]8;;\:]8;id=3503851;file:///home/caff/Documents/footy_analysis/.venv/lib/python3.12/site-packages/soccerdata/whoscored.py#763\763]8;;\

In [10]:
game = ws.read_events(match_id = 1983548)
type(game)

[08/23/26 17:05:25] INFO     Retrieving calendar for ENG-Premier League 2627                       ]8;id=3503928;file:///home/caff/Documents/footy_analysis/.venv/lib/python3.12/site-packages/soccerdata/whoscored.py\whoscored.py]8;;\:]8;id=3503929;file:///home/caff/Documents/footy_analysis/.venv/lib/python3.12/site-packages/soccerdata/whoscored.py#366\366]8;;\

[08/23/26 17:05:33] INFO     [1/10] Retrieving fixtures for ENG-Premier League 2627                ]8;id=3503934;file:///home/caff/Documents/footy_analysis/.venv/lib/python3.12/site-packages/soccerdata/whoscored.py\whoscored.py]8;;\:]8;id=3503935;file:///home/caff/Documents/footy_analysis/.venv/lib/python3.12/site-packages/soccerdata/whoscored.py#397\397]8;;\

[08/23/26 17:05:45] INFO     [2/10] Retrieving fixtures for ENG-Premier League 2627                ]8;id=3503940;file:///home/caff/Documents/footy_analysis/.venv/lib/python3.12/site-packages/soccerdata/whoscored.py\whoscored.py]8;;\:]8;id=3503941;file:///home/caff/Documents/footy_analysis/.venv/lib/python3.12/site-packages/soccerdata/whoscored.py#397\397]8;;\

[08/23/26 17:05:53] INFO     [3/10] Retrieving fixtures for ENG-Premier League 2627                ]8;id=3503946;file:///home/caff/Documents/footy_analysis/.venv/lib/python3.12/site-packages/soccerdata/whoscored.py\whoscored.py]8;;\:]8;id=3503947;file:///home/caff/Documents/footy_analysis/.venv/lib/python3.12/site-packages/soccerdata/whoscored.py#397\397]8;;\

[08/23/26 17:06:02] INFO     [4/10] Retrieving fixtures for ENG-Premier League 2627                ]8;id=3503952;file:///home/caff/Documents/footy_analysis/.venv/lib/python3.12/site-packages/soccerdata/whoscored.py\whoscored.py]8;;\:]8;id=3503953;file:///home/caff/Documents/footy_analysis/.venv/lib/python3.12/site-packages/soccerdata/whoscored.py#397\397]8;;\

[08/23/26 17:06:14] INFO     [5/10] Retrieving fixtures for ENG-Premier League 2627                ]8;id=3503958;file:///home/caff/Documents/footy_analysis/.venv/lib/python3.12/site-packages/soccerdata/whoscored.py\whoscored.py]8;;\:]8;id=3503959;file:///home/caff/Documents/footy_analysis/.venv/lib/python3.12/site-packages/soccerdata/whoscored.py#397\397]8;;\

[08/23/26 17:06:25] INFO     [6/10] Retrieving fixtures for ENG-Premier League 2627                ]8;id=3503964;file:///home/caff/Documents/footy_analysis/.venv/lib/python3.12/site-packages/soccerdata/whoscored.py\whoscored.py]8;;\:]8;id=3503965;file:///home/caff/Documents/footy_analysis/.venv/lib/python3.12/site-packages/soccerdata/whoscored.py#397\397]8;;\

[08/23/26 17:06:37] INFO     [7/10] Retrieving fixtures for ENG-Premier League 2627                ]8;id=3503970;file:///home/caff/Documents/footy_analysis/.venv/lib/python3.12/site-packages/soccerdata/whoscored.py\whoscored.py]8;;\:]8;id=3503971;file:///home/caff/Documents/footy_analysis/.venv/lib/python3.12/site-packages/soccerdata/whoscored.py#397\397]8;;\

[08/23/26 17:06:50] INFO     [8/10] Retrieving fixtures for ENG-Premier League 2627                ]8;id=3503976;file:///home/caff/Documents/footy_analysis/.venv/lib/python3.12/site-packages/soccerdata/whoscored.py\whoscored.py]8;;\:]8;id=3503977;file:///home/caff/Documents/footy_analysis/.venv/lib/python3.12/site-packages/soccerdata/whoscored.py#397\397]8;;\

[08/23/26 17:07:00] INFO     [9/10] Retrieving fixtures for ENG-Premier League 2627                ]8;id=3503982;file:///home/caff/Documents/footy_analysis/.venv/lib/python3.12/site-packages/soccerdata/whoscored.py\whoscored.py]8;;\:]8;id=3503983;file:///home/caff/Documents/footy_analysis/.venv/lib/python3.12/site-packages/soccerdata/whoscored.py#397\397]8;;\

[08/23/26 17:07:14] INFO     [10/10] Retrieving fixtures for ENG-Premier League 2627               ]8;id=3503988;file:///home/caff/Documents/footy_analysis/.venv/lib/python3.12/site-packages/soccerdata/whoscored.py\whoscored.py]8;;\:]8;id=3503989;file:///home/caff/Documents/footy_analysis/.venv/lib/python3.12/site-packages/soccerdata/whoscored.py#397\397]8;;\

[08/23/26 17:07:24] WARNING  /home/caff/Documents/footy_analysis/.venv/lib/python3.12/site-packages ]8;id=3503994;file:///home/caff/.pyenv/versions/3.12.13/lib/python3.12/warnings.py\warnings.py]8;;\:]8;id=3503995;file:///home/caff/.pyenv/versions/3.12.13/lib/python3.12/warnings.py#112\112]8;;\
                             /soccerdata/whoscored.py:421: FutureWarning: The behavior of DataFrame
                             concatenation with empty or all-NA entries is deprecated. In a future
                             version, this will no longer exclude empty or all-NA columns when
                             determining the result dtypes. To retain the old behavior, exclude the
                             relevant entries before the concat operation.
                               pd.concat(all_schedules)

                    INFO     [1/1] Retrieving game with id=1983548                                 ]8;id=3504000;file:///home/caff/Documents/footy_analysis/.venv/lib/python3.12/site-packages/soccerdata/whoscored.py\whoscored.py]8;;\:]8;id=3504001;file:///home/caff/Documents/footy_analysis/.venv/lib/python3.12/site-packages/soccerdata/whoscored.py#689\689]8;;\

pandas.core.frame.DataFrame

In [12]:
game[['player_id', 'player']]

                                                             player_id  \
league             season game
ENG-Premier League 2627   2026-08-22 Hull-Manchester United   495260.0
                          2026-08-22 Hull-Manchester United        NaN
                          2026-08-22 Hull-Manchester United        NaN
                          2026-08-22 Hull-Manchester United   123761.0
                          2026-08-22 Hull-Manchester United   402184.0
...                                                                ...
                          2026-08-22 Hull-Manchester United        NaN
                          2026-08-22 Hull-Manchester United        NaN
                          2026-08-22 Hull-Manchester United        NaN
                          2026-08-22 Hull-Manchester United        NaN
                          2026-08-22 Hull-Manchester United        NaN

                                                                      player
league             season game
ENG-Premier League 2627   2026-08-22 Hull-Manchester United    Patrick Dorgu
                          2026-08-22 Hull-Manchester United              NaN
                          2026-08-22 Hull-Manchester United              NaN
                          2026-08-22 Hull-Manchester United  Bruno Fernandes
                          2026-08-22 Hull-Manchester United    Senne Lammens
...                                                                      ...
                          2026-08-22 Hull-Manchester United              NaN
                          2026-08-22 Hull-Manchester United              NaN
                          2026-08-22 Hull-Manchester United              NaN
                          2026-08-22 Hull-Manchester United              NaN
                          2026-08-22 Hull-Manchester United              NaN

[1574 rows x 2 columns]

In [13]:
import os
DIR = 'utd_games'
num = sum(os.path.isfile(os.path.join(DIR, name)) for name in os.listdir(DIR))
num
games = []
for i in range(num):
    games.append(os.listdir(DIR)[i])
loader = ws.read_events()
for i in range(len(games)):
    game = pd.read_csv(DIR+'/'+games[i])
    id = game.game_id.to_list()
    id = id[0]
    df_players = loader.players(game_id=id)
    path = f'games_players/{id}_players.csv'
    players = game[['player_id', 'player']]
    players.to_csv(path)

[08/23/26 17:08:09] INFO     Retrieving calendar for ENG-Premier League 2627                       ]8;id=3504006;file:///home/caff/Documents/footy_analysis/.venv/lib/python3.12/site-packages/soccerdata/whoscored.py\whoscored.py]8;;\:]8;id=3504007;file:///home/caff/Documents/footy_analysis/.venv/lib/python3.12/site-packages/soccerdata/whoscored.py#366\366]8;;\

[08/23/26 17:08:22] INFO     [1/10] Retrieving fixtures for ENG-Premier League 2627                ]8;id=3504012;file:///home/caff/Documents/footy_analysis/.venv/lib/python3.12/site-packages/soccerdata/whoscored.py\whoscored.py]8;;\:]8;id=3504013;file:///home/caff/Documents/footy_analysis/.venv/lib/python3.12/site-packages/soccerdata/whoscored.py#397\397]8;;\

[08/23/26 17:08:34] INFO     [2/10] Retrieving fixtures for ENG-Premier League 2627                ]8;id=3504018;file:///home/caff/Documents/footy_analysis/.venv/lib/python3.12/site-packages/soccerdata/whoscored.py\whoscored.py]8;;\:]8;id=3504019;file:///home/caff/Documents/footy_analysis/.venv/lib/python3.12/site-packages/soccerdata/whoscored.py#397\397]8;;\

[08/23/26 17:08:43] INFO     [3/10] Retrieving fixtures for ENG-Premier League 2627                ]8;id=3504024;file:///home/caff/Documents/footy_analysis/.venv/lib/python3.12/site-packages/soccerdata/whoscored.py\whoscored.py]8;;\:]8;id=3504025;file:///home/caff/Documents/footy_analysis/.venv/lib/python3.12/site-packages/soccerdata/whoscored.py#397\397]8;;\

[08/23/26 17:08:53] INFO     [4/10] Retrieving fixtures for ENG-Premier League 2627                ]8;id=3504030;file:///home/caff/Documents/footy_analysis/.venv/lib/python3.12/site-packages/soccerdata/whoscored.py\whoscored.py]8;;\:]8;id=3504031;file:///home/caff/Documents/footy_analysis/.venv/lib/python3.12/site-packages/soccerdata/whoscored.py#397\397]8;;\

[08/23/26 17:09:02] INFO     [5/10] Retrieving fixtures for ENG-Premier League 2627                ]8;id=3504036;file:///home/caff/Documents/footy_analysis/.venv/lib/python3.12/site-packages/soccerdata/whoscored.py\whoscored.py]8;;\:]8;id=3504037;file:///home/caff/Documents/footy_analysis/.venv/lib/python3.12/site-packages/soccerdata/whoscored.py#397\397]8;;\

[08/23/26 17:09:12] INFO     [6/10] Retrieving fixtures for ENG-Premier League 2627                ]8;id=3504042;file:///home/caff/Documents/footy_analysis/.venv/lib/python3.12/site-packages/soccerdata/whoscored.py\whoscored.py]8;;\:]8;id=3504043;file:///home/caff/Documents/footy_analysis/.venv/lib/python3.12/site-packages/soccerdata/whoscored.py#397\397]8;;\

[08/23/26 17:09:23] INFO     [7/10] Retrieving fixtures for ENG-Premier League 2627                ]8;id=3504048;file:///home/caff/Documents/footy_analysis/.venv/lib/python3.12/site-packages/soccerdata/whoscored.py\whoscored.py]8;;\:]8;id=3504049;file:///home/caff/Documents/footy_analysis/.venv/lib/python3.12/site-packages/soccerdata/whoscored.py#397\397]8;;\

[08/23/26 17:09:33] INFO     [8/10] Retrieving fixtures for ENG-Premier League 2627                ]8;id=3504054;file:///home/caff/Documents/footy_analysis/.venv/lib/python3.12/site-packages/soccerdata/whoscored.py\whoscored.py]8;;\:]8;id=3504055;file:///home/caff/Documents/footy_analysis/.venv/lib/python3.12/site-packages/soccerdata/whoscored.py#397\397]8;;\

[08/23/26 17:09:46] INFO     [9/10] Retrieving fixtures for ENG-Premier League 2627                ]8;id=3504060;file:///home/caff/Documents/footy_analysis/.venv/lib/python3.12/site-packages/soccerdata/whoscored.py\whoscored.py]8;;\:]8;id=3504061;file:///home/caff/Documents/footy_analysis/.venv/lib/python3.12/site-packages/soccerdata/whoscored.py#397\397]8;;\

[08/23/26 17:09:54] INFO     [10/10] Retrieving fixtures for ENG-Premier League 2627               ]8;id=3504066;file:///home/caff/Documents/footy_analysis/.venv/lib/python3.12/site-packages/soccerdata/whoscored.py\whoscored.py]8;;\:]8;id=3504067;file:///home/caff/Documents/footy_analysis/.venv/lib/python3.12/site-packages/soccerdata/whoscored.py#397\397]8;;\

[08/23/26 17:10:05] WARNING  /home/caff/Documents/footy_analysis/.venv/lib/python3.12/site-packages ]8;id=3504072;file:///home/caff/.pyenv/versions/3.12.13/lib/python3.12/warnings.py\warnings.py]8;;\:]8;id=3504073;file:///home/caff/.pyenv/versions/3.12.13/lib/python3.12/warnings.py#112\112]8;;\
                             /soccerdata/whoscored.py:421: FutureWarning: The behavior of DataFrame
                             concatenation with empty or all-NA entries is deprecated. In a future
                             version, this will no longer exclude empty or all-NA columns when
                             determining the result dtypes. To retain the old behavior, exclude the
                             relevant entries before the concat operation.
                               pd.concat(all_schedules)

                    INFO     [1/380] Retrieving game with id=1983782                               ]8;id=3504078;file:///home/caff/Documents/footy_analysis/.venv/lib/python3.12/site-packages/soccerdata/whoscored.py\whoscored.py]8;;\:]8;id=3504079;file:///home/caff/Documents/footy_analysis/.venv/lib/python3.12/site-packages/soccerdata/whoscored.py#689\689]8;;\

[08/23/26 17:10:31] WARNING  No events found for game 1983782                                      ]8;id=3504084;file:///home/caff/Documents/footy_analysis/.venv/lib/python3.12/site-packages/soccerdata/whoscored.py\whoscored.py]8;;\:]8;id=3504085;file:///home/caff/Documents/footy_analysis/.venv/lib/python3.12/site-packages/soccerdata/whoscored.py#763\763]8;;\

                    INFO     [2/380] Retrieving game with id=1983769                               ]8;id=3504090;file:///home/caff/Documents/footy_analysis/.venv/lib/python3.12/site-packages/soccerdata/whoscored.py\whoscored.py]8;;\:]8;id=3504091;file:///home/caff/Documents/footy_analysis/.venv/lib/python3.12/site-packages/soccerdata/whoscored.py#689\689]8;;\

[08/23/26 17:10:58] WARNING  No events found for game 1983769                                      ]8;id=3504096;file:///home/caff/Documents/footy_analysis/.venv/lib/python3.12/site-packages/soccerdata/whoscored.py\whoscored.py]8;;\:]8;id=3504097;file:///home/caff/Documents/footy_analysis/.venv/lib/python3.12/site-packages/soccerdata/whoscored.py#763\763]8;;\

                    INFO     [3/380] Retrieving game with id=1983780                               ]8;id=3504102;file:///home/caff/Documents/footy_analysis/.venv/lib/python3.12/site-packages/soccerdata/whoscored.py\whoscored.py]8;;\:]8;id=3504103;file:///home/caff/Documents/footy_analysis/.venv/lib/python3.12/site-packages/soccerdata/whoscored.py#689\689]8;;\

[08/23/26 17:11:24] WARNING  No events found for game 1983780                                      ]8;id=3504108;file:///home/caff/Documents/footy_analysis/.venv/lib/python3.12/site-packages/soccerdata/whoscored.py\whoscored.py]8;;\:]8;id=3504109;file:///home/caff/Documents/footy_analysis/.venv/lib/python3.12/site-packages/soccerdata/whoscored.py#763\763]8;;\

                    INFO     [4/380] Retrieving game with id=1983562                               ]8;id=3504114;file:///home/caff/Documents/footy_analysis/.venv/lib/python3.12/site-packages/soccerdata/whoscored.py\whoscored.py]8;;\:]8;id=3504115;file:///home/caff/Documents/footy_analysis/.venv/lib/python3.12/site-packages/soccerdata/whoscored.py#689\689]8;;\

KeyboardInterrupt:

In [14]:
import socceraction.spadl as spadl
x = 1983548
loader = ws.read_events(match_id = x, output_fmt="loader")

[08/23/26 17:14:10] ERROR    Error while scraping                                                    ]8;id=3504121;file:///home/caff/Documents/footy_analysis/.venv/lib/python3.12/site-packages/soccerdata/_common.py\_common.py]8;;\:]8;id=3504122;file:///home/caff/Documents/footy_analysis/.venv/lib/python3.12/site-packages/soccerdata/_common.py#623\623]8;;\
                             https://www.whoscored.com/Regions/252/Tournaments/2/Seasons/11141.
                             Retrying in 0 seconds... (attempt 1 of 5).
                             Traceback (most recent call last):
                               File
                             "/home/caff/Documents/footy_analysis/.venv/lib/python3.12/site-packages
                             /urllib3/connection.py", line 204, in _new_conn
                                 sock = connection.create_connection(
                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                               File
                             "/home/caff/Documents/footy_analysis/.venv/lib/python3.12/site-packages
                             /urllib3/util/connection.py", line 85, in create_connection
                                 raise err
                               File
                             "/home/caff/Documents/footy_analysis/.venv/lib/python3.12/site-packages
                             /urllib3/util/connection.py", line 73, in create_connection
                                 sock.connect(sa)
                             ConnectionRefusedError: [Errno 111] Connection refused

                             The above exception was the direct cause of the following exception:

                             Traceback (most recent call last):
                               File
                             "/home/caff/Documents/footy_analysis/.venv/lib/python3.12/site-packages
                             /urllib3/connectionpool.py", line 788, in urlopen
                                 response = self._make_request(
                                            ^^^^^^^^^^^^^^^^^^^
                               File
                             "/home/caff/Documents/footy_analysis/.venv/lib/python3.12/site-packages
                             /urllib3/connectionpool.py", line 493, in _make_request
                                 conn.request(
                               File
                             "/home/caff/Documents/footy_analysis/.venv/lib/python3.12/site-packages
                             /urllib3/connection.py", line 500, in request
                                 self.endheaders()
                               File
                             "/home/caff/.pyenv/versions/3.12.13/lib/python3.12/http/client.py",
                             line 1353, in endheaders
                                 self._send_output(message_body, encode_chunked=encode_chunked)
                               File
                             "/home/caff/.pyenv/versions/3.12.13/lib/python3.12/http/client.py",
                             line 1113, in _send_output
                                 self.send(msg)
                               File
                             "/home/caff/.pyenv/versions/3.12.13/lib/python3.12/http/client.py",
                             line 1057, in send
                                 self.connect()
                               File
                             "/home/caff/Documents/footy_analysis/.venv/lib/python3.12/site-packages
                             /urllib3/connection.py", line 331, in connect
                                 self.sock = self._new_conn()
                                             ^^^^^^^^^^^^^^^^
                               File
                             "/home/caff/Documents/footy_analysis/.venv/lib/python3.12/site-packages
                             /urllib3/connection.py", line 219, in _new_conn
                                 raise NewConnectionError(
                             urllib3.exceptions.NewConnectionError: HTTPConnection(host='localhost',
                             port=45867): Failed to establish a new connection: [Errno 111]
                             Connection refused

                             The above exception was the direct cause of the following exception:

                             Traceback (most recent call last):
                               File
                             "/home/caff/Documents/footy_analysis/.venv/lib/python3.12/site-packages
                             /soccerdata/_common.py", line 603, in _download_and_save
                                 self._driver.get(url)
                               File
                             "/home/caff/Documents/footy_analysis/.venv/lib/python3.12/site-packages
                             /seleniumbase/core/browser_launcher.py", line 5883, in <lambda>
                                 driver.get = lambda url: uc_special_open_if_cf(
                                                          ^^^^^^^^^^^^^^^^^^^^^^
                               File
                             "/home/caff/Documents/footy_analysis/.venv/lib/python3.12/site-packages
                             /seleniumbase/core/browser_launcher.py", line 510, in
                             uc_special_open_if_cf
                                 driver.execute_script('window.open("%s","_blank");' % url)
                               File
                             "/home/caff/Documents/footy_analysis/.venv/lib/python3.12/site-packages
                             /selenium/webdriver/remote/webdriver.py", line 602, in execute_script
                                 return self.execute(command, {"script": script, "args":
                             converted_args})["value"]
                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                             ^^^^^
                               File
                             "/home/caff/Documents/footy_analysis/.venv/lib/python3.12/site-packages
                             /selenium/webdriver/remote/webdriver.py", line 489, in execute
                                 response = cast(RemoteConnection,
                             self.command_executor).execute(driver_command, params)
                                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                             ^^^^^^^^^^^^^^^^^^^^^
                               File
                             "/home/caff/Documents/footy_analysis/.venv/lib/python3.12/site-packages
                             /selenium/webdriver/remote/remote_connection.py", line 407, in execute
                                 return self._request(command_info[0], url, body=data)
                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                               File
                             "/home/caff/Documents/footy_analysis/.venv/lib/python3.12/site-packages
                             /selenium/webdriver/remote/remote_connection.py", line 431, in _request
                                 response = self._conn.request(method, url, body=body,
                             headers=headers, timeout=self._client_config.timeout)
                                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                               File
                             "/home/caff/Documents/footy_analysis/.venv/lib/python3.12/site-packages
                             /urllib3/_request_methods.py", line 143, in request
                                 return self.request_encode_body(
                                        ^^^^^^^^^^^^^^^^^^^^^^^^^
                               File
                             "/home/caff/Documents/footy_analysis/.venv/lib/python3.12/site-packages
                             /urllib3/_request_methods.py", line 278, in request_encode_body
                                 return self.urlopen(method, url, **extra_kw)
                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                               File
                             "/home/caff/Documents/footy_analysis/.venv/lib/python3.12/site-packages
                             /urllib3/poolmanager.py", line 457, in urlopen
                                 response = conn.urlopen(method, u.request_uri, **kw)
                                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                               File
                             "/home/caff/Documents/footy_analysis/.venv/lib/python3.12/site-packages
                             /urllib3/connectionpool.py", line 872, in urlopen
                                 return self.urlopen(
                                        ^^^^^^^^^^^^^
                               File
                             "/home/caff/Documents/footy_analysis/.venv/lib/python3.12/site-packages
                             /urllib3/connectionpool.py", line 872, in urlopen
                                 return self.urlopen(
                                        ^^^^^^^^^^^^^
                               File
                             "/home/caff/Documents/footy_analysis/.venv/lib/python3.12/site-packages
                             /urllib3/connectionpool.py", line 872, in urlopen
                                 return self.urlopen(
                                        ^^^^^^^^^^^^^
                               File
                             "/home/caff/Documents/footy_analysis/.venv/lib/python3.12/site-packages
                             /urllib3/connectionpool.py", line 842, in urlopen
                                 retries = retries.increment(
                                           ^^^^^^^^^^^^^^^^^^
                               File
                             "/home/caff/Documents/footy_analysis/.venv/lib/python3.12/site-packages
                             /urllib3/util/retry.py", line 543, in increment
                                 raise MaxRetryError(_pool, url, reason) from reason  # type: ignore
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                             urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost',
                             port=45867): Max retries exceeded with url:
                             /session/7ec09e64c8d5786cd273dfc13321199b/execute/sync (Caused by
                             NewConnectionError("HTTPConnection(host='localhost', port=45867):
                             Failed to establish a new connection: [Errno 111] Connection refused"))

[08/23/26 17:14:27] INFO     Retrieving calendar for ENG-Premier League 2627                       ]8;id=3504127;file:///home/caff/Documents/footy_analysis/.venv/lib/python3.12/site-packages/soccerdata/whoscored.py\whoscored.py]8;;\:]8;id=3504128;file:///home/caff/Documents/footy_analysis/.venv/lib/python3.12/site-packages/soccerdata/whoscored.py#366\366]8;;\

[08/23/26 17:19:35] INFO     [1/10] Retrieving fixtures for ENG-Premier League 2627                ]8;id=3504133;file:///home/caff/Documents/footy_analysis/.venv/lib/python3.12/site-packages/soccerdata/whoscored.py\whoscored.py]8;;\:]8;id=3504134;file:///home/caff/Documents/footy_analysis/.venv/lib/python3.12/site-packages/soccerdata/whoscored.py#397\397]8;;\

[08/23/26 17:19:44] INFO     [2/10] Retrieving fixtures for ENG-Premier League 2627                ]8;id=3504139;file:///home/caff/Documents/footy_analysis/.venv/lib/python3.12/site-packages/soccerdata/whoscored.py\whoscored.py]8;;\:]8;id=3504140;file:///home/caff/Documents/footy_analysis/.venv/lib/python3.12/site-packages/soccerdata/whoscored.py#397\397]8;;\

[08/23/26 17:19:54] INFO     [3/10] Retrieving fixtures for ENG-Premier League 2627                ]8;id=3504145;file:///home/caff/Documents/footy_analysis/.venv/lib/python3.12/site-packages/soccerdata/whoscored.py\whoscored.py]8;;\:]8;id=3504146;file:///home/caff/Documents/footy_analysis/.venv/lib/python3.12/site-packages/soccerdata/whoscored.py#397\397]8;;\

[08/23/26 17:20:05] INFO     [4/10] Retrieving fixtures for ENG-Premier League 2627                ]8;id=3504151;file:///home/caff/Documents/footy_analysis/.venv/lib/python3.12/site-packages/soccerdata/whoscored.py\whoscored.py]8;;\:]8;id=3504152;file:///home/caff/Documents/footy_analysis/.venv/lib/python3.12/site-packages/soccerdata/whoscored.py#397\397]8;;\

[08/23/26 17:20:16] INFO     [5/10] Retrieving fixtures for ENG-Premier League 2627                ]8;id=3504157;file:///home/caff/Documents/footy_analysis/.venv/lib/python3.12/site-packages/soccerdata/whoscored.py\whoscored.py]8;;\:]8;id=3504158;file:///home/caff/Documents/footy_analysis/.venv/lib/python3.12/site-packages/soccerdata/whoscored.py#397\397]8;;\

[08/23/26 17:20:24] INFO     [6/10] Retrieving fixtures for ENG-Premier League 2627                ]8;id=3504163;file:///home/caff/Documents/footy_analysis/.venv/lib/python3.12/site-packages/soccerdata/whoscored.py\whoscored.py]8;;\:]8;id=3504164;file:///home/caff/Documents/footy_analysis/.venv/lib/python3.12/site-packages/soccerdata/whoscored.py#397\397]8;;\

[08/23/26 17:20:34] INFO     [7/10] Retrieving fixtures for ENG-Premier League 2627                ]8;id=3504169;file:///home/caff/Documents/footy_analysis/.venv/lib/python3.12/site-packages/soccerdata/whoscored.py\whoscored.py]8;;\:]8;id=3504170;file:///home/caff/Documents/footy_analysis/.venv/lib/python3.12/site-packages/soccerdata/whoscored.py#397\397]8;;\

[08/23/26 17:20:44] INFO     [8/10] Retrieving fixtures for ENG-Premier League 2627                ]8;id=3504175;file:///home/caff/Documents/footy_analysis/.venv/lib/python3.12/site-packages/soccerdata/whoscored.py\whoscored.py]8;;\:]8;id=3504176;file:///home/caff/Documents/footy_analysis/.venv/lib/python3.12/site-packages/soccerdata/whoscored.py#397\397]8;;\

[08/23/26 17:20:55] INFO     [9/10] Retrieving fixtures for ENG-Premier League 2627                ]8;id=3504181;file:///home/caff/Documents/footy_analysis/.venv/lib/python3.12/site-packages/soccerdata/whoscored.py\whoscored.py]8;;\:]8;id=3504182;file:///home/caff/Documents/footy_analysis/.venv/lib/python3.12/site-packages/soccerdata/whoscored.py#397\397]8;;\

[08/23/26 17:21:06] INFO     [10/10] Retrieving fixtures for ENG-Premier League 2627               ]8;id=3504187;file:///home/caff/Documents/footy_analysis/.venv/lib/python3.12/site-packages/soccerdata/whoscored.py\whoscored.py]8;;\:]8;id=3504188;file:///home/caff/Documents/footy_analysis/.venv/lib/python3.12/site-packages/soccerdata/whoscored.py#397\397]8;;\

[08/23/26 17:21:20] WARNING  /home/caff/Documents/footy_analysis/.venv/lib/python3.12/site-packages ]8;id=3504193;file:///home/caff/.pyenv/versions/3.12.13/lib/python3.12/warnings.py\warnings.py]8;;\:]8;id=3504194;file:///home/caff/.pyenv/versions/3.12.13/lib/python3.12/warnings.py#112\112]8;;\
                             /soccerdata/whoscored.py:421: FutureWarning: The behavior of DataFrame
                             concatenation with empty or all-NA entries is deprecated. In a future
                             version, this will no longer exclude empty or all-NA columns when
                             determining the result dtypes. To retain the old behavior, exclude the
                             relevant entries before the concat operation.
                               pd.concat(all_schedules)

                    INFO     [1/1] Retrieving game with id=1983548                                 ]8;id=3504199;file:///home/caff/Documents/footy_analysis/.venv/lib/python3.12/site-packages/soccerdata/whoscored.py\whoscored.py]8;;\:]8;id=3504200;file:///home/caff/Documents/footy_analysis/.venv/lib/python3.12/site-packages/soccerdata/whoscored.py#689\689]8;;\

In [20]:
loader.players(1983548).to_csv('players_vsHull.csv')

In [15]:
type(loader.players(1983548))

pandas.core.frame.DataFrame

In [16]:
import json
with open('player_detail.json', 'w') as f:
        json.dump(loader, f)

TypeError: Object of type OptaLoader is not JSON serializable

In [ ]:
print(loader)

In [17]:
import json
import os

DIR = 'utd_games'
num = sum(os.path.isfile(os.path.join(DIR, name)) for name in os.listdir(DIR))
num
games = []
for i in range(num):
    games.append(os.listdir(DIR)[i])

for i in range(len(games)):
    game = pd.read_csv(DIR+'/'+games[i])
    id = game.game_id.to_list()
    id = id[0]
    df_players = loader.players(game_id=id)
    path = f'games_players/{id}_players.json'
    with open(path, 'w') as f:
        json.dump(df_players, f)

TypeError: Object of type DataFrame is not JSON serializable

In [ ]:
copy_utd_game_list = utd_game_list

In [ ]:
print(copy_utd_game_list[0].game_id[0])

In [ ]:
newid = 'aaa'
path = f'utd_games/{newid}'
path

In [ ]:
x = 5

for i in range(x):
    print(copy_utd_game_list[i].game_id[0])

In [ ]:
print(len(copy_utd_game_list))

In [ ]:
for i in range(len(copy_utd_game_list)):
    try:
        gameid = copy_utd_game_list[i].game_id[0]
        path = f'utd_games/{gameid}.csv'
        copy_utd_game_list[i].to_csv(path)
    except:
        print(copy_utd_game_list[i])

In [ ]:
def collect_teams(league, season,team):
    path = f"C:\\Users\\yukiw\\Documents\\rp\\footy_analysis\\testers\\teams\\{team}" 
    os.mkdir(path)
    ws = sd.WhoScored(leagues=league, seasons=season)
    epl = ws.read_schedule()
    home = epl[epl['home_team'] == team]
    away = epl[epl['away_team'] == team]
    t = pd.concat([home, away])
    list = t['game_id'].to_list()        
    t_list =  []
    for i in range(len(list)):
        game = ws.read_events(match_id = list[i])
        game.to_csv(path + "\\game_" + str(i) + ".csv", index=False)
        t_list.append(game)
    return t_list

In [ ]:
collect_teams(league="ENG-Premiere League", season=2025, team="Manchester United")